apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: web-app-deploy2
spec:
  replicas: 5
  selector:
    matchLabels:
      run: web-app-deploy2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: web-app-deploy2
    spec:
      containers:
      - image: nginx:1.12
        name: web-app
